### ISSUE TITLE
Any workarounds?

### ISSUE THREAD

**Issue by mehmetalianil** [bioothod/trt_crash_efficientnet#1]
I see that this is open for a while in TF repo. 
Have you found any workaround? Did you move onto another model/framework/optimizer etc?

**Comment by bioothod** [comment]
This bug has been fixed here: https://github.com/tensorflow/tensorflow/commit/9bbb12d481de11e2611fa6fbb4dc13cb7bb09176

**Comment by bioothod** [comment]
And the second part is here: https://github.com/tensorflow/tensorflow/pull/37294

**Comment by mehmetalianil** [comment]
But does it also fail as indicated by :https://github.com/tensorflow/tensorflow/issues/37131#issuecomment-596838804
Printing out these:
`2020-11-07 00:15:18.393082: W tensorflow/core/framework/op_kernel.cc:1767] OP_REQUIRES failed at trt_engine_resource_ops.cc:196 : Not found: Container TF-TRT does not exist. (Could not find resource: TF-TRT/TRTEngineOp_0_0)
`
and eventually not showing significant speedup after quantization.

**Comment by bioothod** [comment]
Well, at least it doesn't crash. TRT optimizer is quite limited unfortunately

**Comment by mehmetalianil** [comment]
Well, yes, I will give you that. 
Closing this since it sort of a "fake" issue. 
Cheers.
